# Limpeza e Processamento de Dados

## 1. Importacoes e Carga:

In [19]:
# Importando Bibliotecas
import pandas as pd
import sqlite3 as sq3

In [20]:
# Carregando os arquivos CSV em Dataframes
DF_Mortes = pd.read_csv("Dataset/covid_mortes.csv")
DF_Vacinas = pd.read_csv("Dataset/covid_vacinacao.csv")

In [21]:
DF_Mortes.head()

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,24/02/20,38928341.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/20,38928341.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/20,38928341.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/20,38928341.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/20,38928341.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
DF_Mortes.shape

(100181, 26)

In [22]:
DF_Vacinas.head()

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,24/02/20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,25/02/20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,26/02/20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,27/02/20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,28/02/20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN

In [24]:
DF_Vacinas.shape

(100181, 38)

### -  1.1 Criacao do Banco e Carga de Dados

In [17]:
# Crianco Banco de Dados 
CovidDB = sq3.connect("Database/Covid.db")

In [6]:
# Carregando 2 DataFrames em tabelas diferentes
DF_Mortes.to_sql("Mortes",CovidDB)
DF_Vacinas.to_sql("Vacinas",CovidDB)

100181

### -  1.2 Consultas ao Banco

In [7]:
# Carregando a extensao "SQl" para permitir consultas ao Banco de Dados
%load_ext sql

In [8]:
# Montando conexao com o Banco criado
%sql sqlite:///Database/Covid.db

In [10]:
%%sql

SELECT *
FROM MORTES
LIMIT 10

 * sqlite:///Database/Covid.db
Done.

[(0, 'AFG', 'Asia', 'Afghanistan', '24/02/20', 38928341.0, 1.0, 1.0, None, None, None, None, 0.026, 0.026, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (1, 'AFG', 'Asia', 'Afghanistan', '25/02/20', 38928341.0, 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (2, 'AFG', 'Asia', 'Afghanistan', '26/02/20', 38928341.0, 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (3, 'AFG', 'Asia', 'Afghanistan', '27/02/20', 38928341.0, 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (4, 'AFG', 'Asia', 'Afghanistan', '28/02/20', 38928341.0, 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (5, 'AFG', 'Asia', 'Afghanistan', '29/02/20', 38928341.0, 1.0, 0.0, 0.143, None, None, 0.0, 0.026, 0.0, 0.004, None, None, 0.0, None, None, None, None, None, None, None, None, None),
 (6, 'AFG', 'Asia', 'Afghanistan', '01/03/20', 38928341.0, 1.0, 0.0, 0.143, None, None, 0.0, 0.026, 0.0, 0.004, None, None, 0.0, None, None, None, None, None, None, None, None, None),
 (7, 'AFG', 'Asia', 'Afghanistan', '02/03/20', 38928341.0, 1.0, 0.0, 0.0, None, None, 0.0, 0.026, 0.0, 0.0, None, None, 0.0, None, None, None, None, None, None, None, None, None),
 (8, 'AFG', 'Asia', 'Afghanistan', '03/03/20', 38928341.0, 2.0, 1.0, 0.143, None, None, 0.0, 0.051, 0.026, 0.004, None, None, 0.0, None, None, None, None, None, None, None, None, None),
 (9, 'AFG', 'Asia', 'Afghanistan', '04/03/20', 38928341.0, 4.0, 2.0, 0.429, None, None, 0.0, 0.103, 0.051, 0.011, None, None, 0.0, None, None, None, None, None, None, None, None, None)]

In [11]:
%%sql

SELECT *
FROM VACINAS
LIMIT 10

 * sqlite:///Database/Covid.db
Done.

[(0, 'AFG', 'Asia', 'Afghanistan', '24/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (1, 'AFG', 'Asia', 'Afghanistan', '25/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (2, 'AFG', 'Asia', 'Afghanistan', '26/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (3, 'AFG', 'Asia', 'Afghanistan', '27/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (4, 'AFG', 'Asia', 'Afghanistan', '28/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (5, 'AFG', 'Asia', 'Afghanistan', '29/02/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (6, 'AFG', 'Asia', 'Afghanistan', '01/03/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 27.78, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (7, 'AFG', 'Asia', 'Afghanistan', '02/03/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 27.78, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (8, 'AFG', 'Asia', 'Afghanistan', '03/03/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 27.78, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None),
 (9, 'AFG', 'Asia', 'Afghanistan', '04/03/20', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 27.78, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511, None)]

## 2. Limpeza de Dados:

### -  2.1 Tratando Valores Ausentes

### -  2.2 Detectando/Tratando Outliers

### -  2.3 Detectando/Tratando Registros Duplicados

### -  2.4 Reorganizando Dados

## 3. Processando Dados:

### -  3.1 Traformacao de Atributos (Parsing)

### -  3.2 Mapeamento

### -  3.3 Filtragem Agregacao e Sumarizacao

### -  3.4 Enriquecimento e Imputacao de Dados